language: java
sudo: required
dist: precise

matrix:
  include:
    - jdk: oraclejdk9 # JDK 9-ea+174 provided by Travis will be replaced by 9+177 in "before_install"
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install oracle-9-installer
        - remove_dir_from_path $JAVA_HOME/bin
        - export JAVA_HOME=/usr/lib/jvm/java-9-oracle
        - export PATH=$JAVA_HOME/bin:$PATH
        - java -version